name: "publish-android"
# copy of https://v2.tauri.app/distribute/pipelines/github/
# edited using https://github.com/charlesschaefer/faire-todo-app/blob/main/.github/workflows/android.yml

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  publish-android:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: "Install: Rust Stable with android targets"
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown,aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

      - name: "Cache: Cargo"
        uses: actions/cache@v4
        id: cache-cargo
        with:
          path: target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: "Cache: Tauri Trunk"
        uses: actions/cache@v4
        id: cache-cargo-global
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-tauri-trunk-${{ hashFiles('./src-tauri/Cargo.toml') }}

      - name: "Install: Tauri-CLI and Trunk"
        if: steps.cache-cargo-global.outputs.cache-hit != 'true'
        run: cargo install tauri-cli trunk --locked

      - name: "Setup: JDK"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: "Setup: Android SDK"
        uses: android-actions/setup-android@v3

      - name: "Setup: Android NDK"
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27d
          link-to-sdk: true

      - name: "Setup: Android Signing"
        run: |
          cd src-tauri/gen/android
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > keystore.properties
          echo "password=${{ secrets.ANDROID_KEY_PASSWORD }}" >> keystore.properties
          base64 -d <<< "${{ secrets.ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties

      - name: "Build: APK and AAB"
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: cargo tauri android build

      - name: "Create: Release"
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          draft: true
          generate_release_notes: true
          files: |
            /home/runner/work/rebalax/rebalax/src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk
            /home/runner/work/rebalax/rebalax/src-tauri/gen/android/app/build/outputs/bundle/universalRelease/app-universal-release.aab
